# Kotlin Gradle CircleCI 2.0 configuration file
#
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/app
    environment:
      CC_TEST_REPORTER_ID: 1c273b4ec0fadb0df1aa101329e35d9e88f39ad5cee2de302c1a2c3e765f4764
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: ./gradlew clean build
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: ~/app
          paths:
            - libs/*.jar
            - build/libs/*.jar
            - Dockerfile

# define workflows that are triggered on different events
workflows:
  version: 2

  # run on every commit on master
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - aws-ecr/build-and-push-image:
          repo: test/app
          tag: '${CIRCLE_SHA1}'
          checkout: false
          attach-workspace: true
          workspace-root: ~/app
          requires:
            - build
          filters:
            branches:
              only: master
