CREATE TABLE public.author (
    "id"    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "email" VARCHAR(255) NOT NULL,
    "name"  VARCHAR(255) NOT NULL,
    "pass"  VARCHAR(255) NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("email")
);

CREATE TABLE public.role (
    "id"    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name"  VARCHAR(255) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE public.privilege (
    "id"    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name"  VARCHAR(255) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE public.course (
    "id"        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "category"  VARCHAR(255),
    "name"      VARCHAR(255),
    PRIMARY KEY ("id")
);

CREATE TABLE public.author_roles (
    "author_id"       BIGINT NOT NULL,
    "role_id"       BIGINT NOT NULL,
    CONSTRAINT "fk_author_roles_author_id" FOREIGN KEY ("author_id") REFERENCES "author" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_author_roles_role_id" FOREIGN KEY ("role_id") REFERENCES "role" ("id") ON DELETE CASCADE
);

CREATE TABLE public.role_privileges (
    "role_id"       BIGINT NOT NULL,
    "privilege_id"  BIGINT NOT NULL,
    CONSTRAINT "fk_role_privileges_role_id" FOREIGN KEY ("role_id") REFERENCES "role" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_role_privileges_privilege_id" FOREIGN KEY ("privilege_id") REFERENCES "privilege" ("id") ON DELETE CASCADE
);

CREATE TABLE public.topic (
    "id"            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "creation_date" TIMESTAMP WITH TIME ZONE DEFAULT now()  NOT NULL,
    "message"       TEXT                                    NOT NULL,
    "status"        VARCHAR(255)                            NOT NULL,
    "title"         VARCHAR(255)                            NOT NULL,
    "author_id"     BIGINT                                  NOT NULL,
    "course_id"     BIGINT                                  NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_topic_author_id" FOREIGN KEY ("author_id") REFERENCES "author" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_topic_course_id" FOREIGN KEY ("course_id") REFERENCES "course" ("id") ON DELETE CASCADE
);

CREATE TABLE public.answer (
    "id"            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "creation_date" TIMESTAMP WITH TIME ZONE    DEFAULT now()   NOT NULL,
    "message"       TEXT                                        NOT NULL,
    "solution"      BOOLEAN                     DEFAULT false   NOT NULL,
    "author_id"     BIGINT                                      NOT NULL,
    "topic_id"      BIGINT                                      NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_answer_author_id" FOREIGN KEY ("author_id") REFERENCES "author" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_answer_topic_id" FOREIGN KEY ("topic_id") REFERENCES "topic" ("id") ON DELETE CASCADE
);
