name: GitHub Security Alerts for Jira

on:
  # schedule:
    # Every 5 minutes
    # - cron: '*/5 * * * *'
  push:
    branches:
      - "**"

jobs:
  sync-github-alerts-jira:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: rribeiro1/github-alerts-jira-sync@main
        with:
          github_token: ${{ secrets.GH_SECURITY_TOKEN }}
          repo_owner: rribeiro1
          repo_name: forum-kotlin-spring-boot
          jira_server: ${{ secrets.JIRA_HOST }}
          jira_username: ${{ secrets.JIRA_USER }}
          jira_token: ${{ secrets.JIRA_API_TOKEN }}
          jira_project_key: RIB
          jira_custom_fields: '{"customfield_10037":"Backend"}'
          jira_summary_prefix: "[Security]"