name: GitHub Security Alerts for Jira

on:
  # schedule:
    # Every 5 minutes
    # - cron: '*/5 * * * *'
  push:
    branches:
      - "**"

jobs:
  sync-github-alerts-jira:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: rribeiro1/github-alerts-jira-sync@v0.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECURITY_TOKEN }}
          REPO_OWNER: rribeiro1
          REPO_NAME: forum-kotlin-spring-boot
          JIRA_SERVER: ${{ secrets.JIRA_HOST }}
          JIRA_USERNAME: ${{ secrets.JIRA_USER }}
          JIRA_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_KEY: RIB
          JIRA_CUSTOM_FIELDS: '{"customfield_10037":"Backend"}'
          JIRA_SUMMARY_PREFIX: "[Security]"