name: Post Actions

on:
  push:
    branches:
      - '**'
  pull_request_target:

jobs:
  post-actions:
    name: Post Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update DataDog agent
        run: echo ${{ github.event.pull_request.title }}
