name: Post Actions

on:
  push:
    branches:
      - '**'
  pull_request_target:

jobs:
  post-actions:
    name: Post Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update DataDog agent
        uses: actions/github-script@v3
        with:
          script: |
            console.log(context.payload.pull_request)
