name: Post Actions

on:
  pull_request:
  push:
    branches:
      - '**'
  pull_request_target:

jobs:
  post-actions:
    name: Post Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: auto-merge

      - name: Update DataDog agent
        shell: bash
        run: |
          echo ${{ github.event.pull_request.title }}
          TITLE="${{ github.event.pull_request.title }}"
          VERSION=v"$(echo $TITLE | sed 's/^.* \([^ ][^ ]*\)/\1/g')"
          echo $VERSION
          wget -O dd-java-agent.jar "https://github.com/DataDog/dd-trace-java/releases/download/${VERSION}/dd-java-agent.jar"
          mv dd-java-agent.jar libs/dd-java-agent.jar
          ls
          echo $(git status)
          git status
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add libs/dd-java-agent.jar
          git commit -m "Upgrade DataDog agent for Java to v${VERSION}"
          git push