name: Build Container Workflow

on:
  workflow_call:
    inputs:
      active:
        type: boolean
        default: false
        required: false

jobs:
  build:
    name: Reusable Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |
          if [[ "${inputs.active}" == true ]]; then
            echo "Condition is true"
          else
            echo "Condition is false"
          fi
        shell: bash
